export const INIT_ITEMS = 'INIT_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const TOGGLE_SIDEDRAWER = "TOGGLE_SIDEDRAWER";
export const LOADING_ITEMS = "LOADING_ITEMS";